name: aoa
channels:
  - conda-forge
  - R
  - defaults
dependencies:
  ##- _anaconda_depends=2023.03
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  #- _r-mutex=1.0.1
  #- alsa-lib=1.2.11
  ##- anaconda=custom
  ##- anaconda-client=1.11.1
  ##- anaconda-navigator=1.9.12
  ##- annexremote=1.5.0
  - anyio=3.5.0
  #- aoo-mozilla-en-dict-au=2024.03.01
  #- aoo-mozilla-en-dict-ca=2024.03.01
  #- aoo-mozilla-en-dict-gb=2024.03.01
  #- aoo-mozilla-en-dict-us=2024.03.01
  #- aoo-mozilla-en-dict-za=2024.03.01
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.2.3
  - asttokens=2.0.5
  #- async-lru=2.0.4
  #- attr=2.5.1
  - attrs=22.1.0
  - babel=2.11.0
  - beautifulsoup4=4.11.1
  #- binutils_impl_linux-64=2.40
  - bleach=4.1.0
  #- brotli-python=1.1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.19.0
  - ca-certificates=2023.01.10
  #- cached-property=1.5.2
  #- cached_property=1.5.2
  #- cairo=1.18.0
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - comm=0.1.2
  - curl=7.88.1
  #- dart-sass=1.58.3
  - dbus=1.13.18
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  #- deno=1.28.2
  #- deno-dom=0.1.35
  - entrypoints=0.4
  #- esbuild=0.19.2
  #- exceptiongroup=1.2.0
  - executing=0.8.3
  - expat=2.4.9
  #- font-ttf-dejavu-sans-mono=2.37
  #- font-ttf-inconsolata=3.000
  #- font-ttf-source-code-pro=2.038
  #- font-ttf-ubuntu=0.83
  - fontconfig=2.14.1
  #- fonts-conda-ecosystem=1
  #- fonts-conda-forge=1
  #- fqdn=1.5.1
  - freetype=2.12.1
  #- fribidi=1.0.10
  #- gcc_impl_linux-64=13.2.0
  - gettext=0.21.0
  #- gettext-tools=0.22.5
  #- gfortran_impl_linux-64=13.2.0
  - giflib=5.2.1
  - glib=2.69.1
  #- glib-tools=2.78.1
  #- graphite2=1.3.13
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  #- gxx_impl_linux-64=13.2.0
  #- h11=0.14.0
  #- h2=4.1.0
  #- harfbuzz=8.3.0
  #- hpack=4.0.0
  #- httpcore=1.0.5
  #- httpx=0.27.0
  #- hunspell=1.7.2
  #- hunspell-en=2024.03.01
  #- hyperframe=6.0.1
  - icu=58.2
  - idna=3.4
  #- importlib-metadata=7.1.0
  - importlib_metadata=6.0.0
  - importlib_resources=5.2.0
  - ipykernel=6.19.2
  - ipython=8.10.0
  #- isoduration=20.11.0
  - jedi=0.18.1
  - jinja2=3.1.2
  - json5=0.9.6
  #- jsonpointer=2.4
  - jsonschema=4.17.3
  #- jsonschema-specifications=2023.12.1
  #- jsonschema-with-format-nongpl=4.21.1
  #- jupyter-lsp=2.2.4
  - jupyter_client=7.4.9
  - jupyter_core=5.3.0
  #- jupyter_events=0.10.0
  - jupyter_server=1.23.4
  #- jupyter_server_terminals=0.5.3
  - jupyterlab=3.5.3
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.21.0
  #- kernel-headers_linux-64=2.6.32
  #- keyutils=1.6.1
  - krb5=1.19.4
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  #- libasprintf=0.22.5
  #- libasprintf-devel=0.22.5
  #- libblas=3.9.0
  #- libboost=1.82.0
  #- libcap=2.69
  #- libcblas=3.9.0
  - libclang=13.0.0
  #- libclang13=15.0.7
  #- libcups=2.3.3
  - libcurl=7.88.1
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libev=4.33
  - libevent=2.1.12
  #- libexpat=2.6.2
  - libffi=3.3
  #- libflac=1.4.3
  #- libgcc-devel_linux-64=13.2.0
  - libgcc-ng=12.1.0
  #- libgcrypt=1.10.3
  #- libgettextpo=0.22.5
  #- libgettextpo-devel=0.22.5
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  #- libglib=2.78.1
  - libgomp=12.1.0
  #- libgpg-error=1.48
  #- libiconv=1.17
  #- libjpeg-turbo=2.1.5.1
  #- liblapack=3.9.0
  - libllvm10=10.0.1
  - libllvm11=11.1.0
  - libnghttp2=1.46.0
  #- libnsl=2.0.1
  #- libogg=1.3.4
  #- libopenblas=0.3.27
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=12.9
  #- libsanitizer=13.2.0
  #- libsndfile=1.2.2
  - libsodium=1.0.18
  #- libsqlite=3.45.2
  - libssh2=1.10.0
  #- libstdcxx-devel_linux-64=13.2.0
  - libstdcxx-ng=12.1.0
  #- libsystemd0=255
  - libtiff=4.5.0
  - libuuid=1.41.5
  #- libvorbis=1.3.7
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  #- libxcrypt=4.4.36
  - libxkbcommon=1.0.1
  - libxml2=2.9.14
  #- libzlib=1.2.13
  - lz4-c=1.9.4
  #- make=4.3
  - markupsafe=2.1.1
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  #- mathjax=2.7.7
  - mistune=0.8.4
  #- mpg123=1.32.6
  #- mysql-common=8.0.33
  #- mysql-libs=8.0.33
  - nbclient=0.5.13
  - nbconvert=6.5.4
  - nbformat=5.7.0
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - notebook=6.5.3
  - notebook-shim=0.2.2
  - nspr=4.33
  - nss=3.74
  - numpy=1.21.5
  #- openjdk=20.0.2
  - pyopenssl=23.0.0
  #- overrides=7.7.0
  - packaging=23.0
  - pandas=1.5.3
  #- pandoc=3.1.1
  - pandocfilters=1.5.0
  #- pango=1.50.14
  - parso=0.8.3
  - pcre2=10.37
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.0.1
  #- pixman=0.43.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=2.5.2
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  #- pthread-stubs=0.4
  - ptyprocess=0.7.0
  #- pulseaudio-client=16.1
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.11.2
  - pysocks=1.7.1
  - python=3.8.3
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  #- python-json-logger=2.0.7
  #- python-tzdata=2024.1
  - python_abi=3.8
  - pytz=2022.7
  - pyyaml=6.0
  - pyzmq=23.2.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  #- quarto=1.3.450
  - r-askpass=1.2.0
  - r-assertthat=0.2.1
  - r-backports=1.4.1
  - r-base=4.3.1
  - r-base64enc=0.1_3
  - r-bit=4.0.5
  - r-bit64=4.0.5
  - r-blob=1.2.4
  - r-bookdown=0.36
  - r-brio=1.1.4
  - r-broom=1.0.5
  - r-bslib=0.7.0
  - r-cachem=1.0.8
  - r-callr=3.7.6
  - r-cellranger=1.1.0
  - r-cli=3.6.2
  - r-clipr=0.8.0
  - r-colorspace=2.1_0
  - r-conflicted=1.2.0
  - r-cowplot=1.1.3
  - r-cpp11=0.4.7
  - r-crayon=1.5.2
  - r-curl=5.1.0
  - r-data.table=1.15.2
  - r-dbi=1.2.2
  - r-dbplyr=2.4.0
  - r-desc=1.4.3
  - r-diffobj=0.3.5
  - r-digest=0.6.35
  - r-dplyr=1.1.4
  - r-dtplyr=1.3.1
  - r-ellipsis=0.3.2
  - r-evaluate=0.23
  - r-fansi=1.0.6
  - r-farver=2.1.1
  - r-fastmap=1.1.1
  - r-fontawesome=0.5.2
  - r-forcats=1.0.0
  - r-fs=1.6.3
  - r-gargle=1.5.2
  - r-generics=0.1.3
  - r-ggplot2=3.5.0
  - r-glue=1.7.0
  - r-googledrive=2.1.1
  - r-googlesheets4=1.1.1
  - r-gtable=0.3.4
  - r-haven=2.5.4
  - r-highr=0.10
  - r-hms=1.1.3
  - r-htmltools=0.5.8.1
  - r-httr=1.4.7
  - r-ids=1.0.1
  - r-isoband=0.2.7
  - r-jquerylib=0.1.4
  - r-jsonlite=1.8.8
  - r-knitr=1.46
  - r-labeling=0.4.3
  - r-lattice=0.22_6
  - r-lifecycle=1.0.4
  - r-lubridate=1.9.3
  - r-magrittr=2.0.3
  - r-mass=7.3_60
  - r-matrix=1.6_5
  - r-memoise=2.0.1
  - r-mgcv=1.9_1
  - r-mime=0.12
  - r-modelr=0.1.11
  - r-munsell=0.5.1
  - r-nlme=3.1_164
  - r-openssl=2.1.1
  - r-papaja=0.1.2
  - r-pillar=1.9.0
  - r-pkgbuild=1.4.4
  - r-pkgconfig=2.0.3
  - r-pkgload=1.3.4
  - r-praise=1.0.0
  - r-prettyunits=1.2.0
  - r-processx=3.8.4
  - r-progress=1.2.3
  - r-ps=1.7.6
  - r-purrr=1.0.2
  - r-r6=2.5.1
  - r-ragg=1.2.5
  - r-rappdirs=0.3.3
  - r-rcolorbrewer=1.1_3
  - r-readods=2.2.0
  - r-readr=2.1.5
  - r-readxl=1.4.3
  - r-rematch=2.0.0
  - r-rematch2=2.1.2
  - r-renv=1.0.5
  - r-reprex=2.1.0
  - r-rlang=1.1.3
  - r-rmarkdown=2.26
  - r-rmdfiltr=0.1.3
  - r-rprojroot=2.0.4
  - r-rstudioapi=0.16.0
  - r-rvest=1.0.4
  - r-sass=0.4.9
  - r-scales=1.3.0
  - r-selectr=0.4_2
  - r-stringi=1.8.3
  - r-stringr=1.5.1
  - r-sys=3.4.2
  - r-systemfonts=1.0.5
  - r-testthat=3.2.1
  - r-textshaping=0.3.7
  - r-tibble=3.2.1
  - r-tidyr=1.3.1
  - r-tidyselect=1.2.0
  - r-tidyverse=2.0.0
  - r-timechange=0.3.0
  - r-tinylabels=0.2.4
  - r-tinytex=0.50
  - r-tzdb=0.4.0
  - r-utf8=1.2.4
  - r-uuid=1.2_0
  - r-vctrs=0.6.5
  - r-viridislite=0.4.2
  - r-vroom=1.6.5
  - r-waldo=0.5.2
  - r-withr=3.0.0
  - r-xfun=0.43
  - r-xml2=1.3.6
  - r-yaml=2.3.8
  - r-zip=2.3.0
  - readline=8.2
  #- referencing=0.34.0
  - requests=2.28.1
  #- rfc3339-validator=0.1.4
  #- rfc3986-validator=0.1.1
  #- rpds-py=0.18.0
  #- rstudio-desktop=2022.12.0
  #- sed=4.8
  - send2trash=1.8.0
  - setuptools=65.6.3
  - six=1.16.0
  - sniffio=1.2.0
  #- soci-core=4.0.3
  #- soci-postgresql=4.0.3
  #- soci-sqlite=4.0.3
  - soupsieve=2.4
  - sqlite=3.41.1
  - stack_data=0.2.0
  #- sysroot_linux-64=2.12
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.12
  #- tktable=2.10
  - tomli=2.0.1
  - tornado=6.2
  - traitlets=5.7.1
  #- types-python-dateutil=2.9.0.20240316
  - typing-extensions=4.1.1
  - typing_extensions=4.4.0
  #- typing_utils=0.1.0
  #- tzdata=2024a
  #- uri-template=1.3.0
  - urllib3=1.26.15
  - wcwidth=0.2.5
  #- webcolors=1.13
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.38.4
  #- xcb-util=0.4.0
  #- xcb-util-image=0.4.0
  #- xcb-util-keysyms=0.4.0
  #- xcb-util-renderutil=0.3.9
  #- xcb-util-wm=0.4.1
  #- xkeyboard-config=2.41
  #- xorg-compositeproto=0.4.2
  #- xorg-damageproto=1.2.1
  #- xorg-fixesproto=5.0
  #- xorg-inputproto=2.3.2
  #- xorg-kbproto=1.0.7
  #- xorg-libice=1.1.1
  #- xorg-libsm=1.2.4
  #- xorg-libx11=1.8.9
  #- xorg-libxau=1.0.11
  #- xorg-libxcomposite=0.4.6
  #- xorg-libxcursor=1.2.0
  #- xorg-libxdamage=1.1.5
  #- xorg-libxdmcp=1.1.3
  #- xorg-libxext=1.3.4
  #- xorg-libxfixes=5.0.3
  #- xorg-libxi=1.7.10
  #- xorg-libxrandr=1.5.2
  #- xorg-libxrender=0.9.11
  #- xorg-libxscrnsaver=1.2.3
  #- xorg-libxt=1.3.0
  #- xorg-libxtst=1.2.3
  #- xorg-randrproto=1.5.0
  #- xorg-recordproto=1.14.2
  #- xorg-renderproto=0.11.1
  #- xorg-scrnsaverproto=1.2.2
  #- xorg-util-macros=1.19.3
  #- xorg-xextproto=7.3.0
  #- xorg-xf86vidmodeproto=2.3.1
  #- xorg-xproto=7.0.31
  - xz=5.2.10
  - yaml=0.2.5
  #- yaml-cpp=0.6.3
  - zeromq=4.3.4
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.4
